
name: basic workflow demo

on:
    workflow_dispatch:

   
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
  build-api:
        runs-on: windows-latest
        steps:
            - run : echo "builing Api"
  build-db:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run : echo "builing  db"