
name: basic workflow demo

on:
  push: 
    branches : ["master"]
    
  pull_request:
    branches : ["master"]

   
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   
  build-api:
        runs-on: windows-latest
        steps:
            - run : echo"builind Api"
  build-db:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run : echo"builind db"