name: user depicted env vars

on:
  workflow_dispatch:

jobs:
  custom_GITHUB_ENV:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value of env vars
        id: step_one
        run: |
          echo "action_state=blue" >> $GITHUB_ENV

      - name: Use the value of env vars
        id: step_two
        run: |
          source $GITHUB_ENV
          echo $action_state
